# File: pubspec.yaml

name: wellbeing_mobile_app
description: A new Flutter project for wellbeing tracking.
publish_to: 'none' # Remove this line if you plan to publish

version: 1.0.0+1

environment:
  # The constraints for your Dart SDK are set to accommodate recent Flutter versions
  # but allow flexibility.
  sdk: '>=3.0.0 <4.0.0'

# ===============================================
# ALL PROJECT DEPENDENCIES ARE LISTED BELOW
# ===============================================
dependencies:
  flutter:
    sdk: flutter

  # --- CORE FIREBASE PACKAGES (Required for Auth & Data) ---
  firebase_core: # Using the latest compatible version
  firebase_auth: # Using the latest compatible version
  cloud_firestore: # Using the latest compatible version

  # --- UTILITY PACKAGES (Required for App Functionality) ---
  intl: ^0.18.0 # For DateFormat
  flutter_tts: ^3.7.0 # Text-to-Speech
  shared_preferences: ^2.2.2 # Persisting data
  cupertino_icons: ^1.0.6
  
  # --- NEW MISSING PACKAGES ---
  # We use these broad constraints to allow the pub system to find the newest working versions.
  http: 
  uuid: 
  font_awesome_flutter: 
  fl_chart: # CRITICAL FIX: Removing the version constraint to allow update
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter Packages 
  flutter_lints: ^3.0.0
  lints: ^3.0.0
  
  # Required for Firebase configuration tool
  flutterfire_cli: 

# ===============================================
# FLUTTER CONFIGURATION
# ===============================================
flutter:
  uses-material-design: true

  
