# File: pubspec.yaml

name: wellbeing_mobile_app
description: A new Flutter project for wellbeing tracking.
publish_to: 'none' # Remove this line if you plan to publish

version: 1.0.0+1

environment:
  # The constraints for your Dart SDK are set to accommodate recent Flutter versions
  # but allow flexibility.
  sdk: '>=3.0.0 <4.0.0'

# ===============================================
# ALL PROJECT DEPENDENCIES ARE LISTED BELOW
# ===============================================
dependencies:
  flutter:
    sdk: flutter

  # --- CORE FIREBASE PACKAGES (Fixed to known stable versions) ---
  firebase_core: ^4.2.0    
  firebase_auth: ^6.1.1    
  cloud_firestore: ^6.0.3  

  # --- UTILITY PACKAGES (Updated to latest major versions) ---
  intl: ^0.20.2             # Updated
  flutter_tts: ^4.2.3       # Updated
  shared_preferences: ^2.2.2 
  cupertino_icons: ^1.0.6
  
  # --- NEW MISSING PACKAGES ---
  http: ^1.2.1               
  uuid: ^4.3.1               
  font_awesome_flutter: ^10.7.0 
  fl_chart: ^0.68.0          
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linter Packages (Updated to latest major versions)
  flutter_lints: ^6.0.0
  lints: ^6.0.0
  
  # Required for Firebase configuration tool (CRITICAL FIX: Downgraded)
  flutterfire_cli: ^0.1.1+2 # Downgraded to resolve conflict with intl ^0.20.2

# ===============================================
# FLUTTER CONFIGURATION
# ===============================================
flutter:
  uses-material-design: true

  # Add assets below to include them in your application
  assets:
    - images/a_dat_burr.jpeg
    - images/a_dat_ham.jpeg
