name: wellbeing_mobile_app
description: A new Flutter project for a Wellbeing Coach app.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  
  # Core Packages
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.2
  
  # For Date Formatting (used in GoalScreen)
  intl: ^0.19.0 # Note: Using latest stable version
  
  # For generating unique IDs (used in GoalModel)
  uuid: ^4.3.3

  # === MISSING PACKAGES (REQUIRED BY ANALYSIS) ===
  # Firebase Core and Services
  firebase_core: ^2.25.4  # Core Firebase service
  firebase_auth: ^4.17.4  # For authentication
  cloud_firestore: ^4.15.4 # For Firestore database
  
  # Geolocation and Weather APIs
  geolocator: ^11.0.0      # For determining device location
  http: ^1.2.1            # For API service (Weather/Quote fetch)
  
  # Text-to-Speech (TTS)
  flutter_tts: ^4.0.2     # For text-to-speech functionality
  
  # Charts (for StatsChart widget)
  fl_chart: ^0.68.0       # For displaying statistics charts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/