name: wellbeing_mobile_app
description: A new Flutter project for wellbeing tracking.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# =========================================================
# ALL PROJECT DEPENDENCIES ARE LISTED BELOW
# =========================================================
dependencies:
  flutter:
    sdk: flutter

  # --- CORE FIREBASE PACKAGES (Required for Auth & Data) ---
  firebase_core: ^2.32.0 
  firebase_auth: ^4.20.0 
  cloud_firestore: ^4.17.5 
  
  # --- UTILITY PACKAGES (Required for App Functionality) ---
  intl: ^0.20.2          # Required for DateFormat (Fixes previous code errors)
  flutter_tts: ^4.2.3    # Text-to-Speech
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6

  # --- NEW MISSING PACKAGES (CRITICAL FIXES for 53 Errors) ---
  http: ^1.2.1               # Required for API calls (e.g., weather or external data)
  uuid: ^4.4.0               # Required for generating unique IDs (e.g., goals)
  font_awesome_flutter: ^10.7.0 # Required for FontAwesome Icons
  fl_chart: ^0.68.0          # Required for statistical charts
  # --------------------------------------------------------

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section below.
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg