// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoaHMSLsEiq1p59aOf0jhMJNP-BfGbM0E',
    appId: '1:220816300373:web:79c0d147907828893e37dc',
    messagingSenderId: '220816300373',
    projectId: 'wellbeing-41b07',
    authDomain: 'wellbeing-41b07.firebaseapp.com',
    storageBucket: 'wellbeing-41b07.firebasestorage.app',
    measurementId: 'G-VXYHWW31JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqoFOECS53v4AoWyapjbTDtbvLFuX2ySE',
    appId: '1:220816300373:android:e776800cbf6f4f983e37dc',
    messagingSenderId: '220816300373',
    projectId: 'wellbeing-41b07',
    storageBucket: 'wellbeing-41b07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjOlRmKxiNkzjte77Bl8m5xESnlDBRYFM',
    appId: '1:220816300373:ios:1de623920c3d249e3e37dc',
    messagingSenderId: '220816300373',
    projectId: 'wellbeing-41b07',
    storageBucket: 'wellbeing-41b07.firebasestorage.app',
    iosBundleId: 'com.example.wellbeingMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjOlRmKxiNkzjte77Bl8m5xESnlDBRYFM',
    appId: '1:220816300373:ios:1de623920c3d249e3e37dc',
    messagingSenderId: '220816300373',
    projectId: 'wellbeing-41b07',
    storageBucket: 'wellbeing-41b07.firebasestorage.app',
    iosBundleId: 'com.example.wellbeingMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoaHMSLsEiq1p59aOf0jhMJNP-BfGbM0E',
    appId: '1:220816300373:web:7316e9106cce3d583e37dc',
    messagingSenderId: '220816300373',
    projectId: 'wellbeing-41b07',
    authDomain: 'wellbeing-41b07.firebaseapp.com',
    storageBucket: 'wellbeing-41b07.firebasestorage.app',
    measurementId: 'G-7CJCFF87M1',
  );
}
